import {recommend} from "../engine/recommend";import type {CannotDetermineReason,Dataset,EngineInput,Result} from "../engine/types";
export const brandInputs={Bauer:{slug:"bauer",method:"floor_to_knee",category:true,height:false,ktt:false},CCM:{slug:"ccm",method:"floor_to_knee",category:false,height:true,ktt:false},TRUE:{slug:"true",method:"floor_to_knee",category:true,height:false,ktt:false},Warrior:{slug:"warrior",method:"floor_to_knee",category:false,height:true,ktt:true},"Brian's":{slug:"brians",method:"ankle_to_knee",category:false,height:false,ktt:true},Vaughn:{slug:"vaughn",method:"ankle_to_knee",category:false,height:false,ktt:false}} as const;
export type CalculatorBrand=keyof typeof brandInputs;export const supportedPreset=(v:string|null)=>Object.entries(brandInputs).find(([,c])=>c.slug===v?.toLowerCase())?.[0] as CalculatorBrand|undefined;export const toInches=(v:number,u:"in"|"cm")=>u==="cm"?v/2.54:v;
export const reasonCopy:Record<CannotDetermineReason,string>={missing_category:"Choose the age or level category used by this chart.",missing_height:"Add standing height to check this brand's published anchor.",missing_floor_to_knee:"Add the floor-to-knee measurement required by this chart.",source_gap:"The reviewed chart has no rule for this measurement. Recheck it or consult a qualified fitter.",personal_preference_not_base_size_rule:"Thigh-rise preference cannot determine the sourced base pad size.",extension_not_available:"The reviewed chart marks this extension as unavailable.",no_official_mapping:"No reviewed official mapping supports a recommendation for this brand."};
export const statusHeading=(r:Result)=>r.status==="candidate"?"Recommended chart size":r.status==="adjacent_sizes"?"Adjacent chart sizes":r.status==="conflict"?"Measurements conflict":"Cannot determine a size";
const measurementNames={floor_to_knee:"floor-to-knee",height:"standing height",height_anchor:"standing height",ankle_to_knee:"ankle-to-knee",knee_to_thigh:"knee-to-thigh"} as const;
const formatNumber=(value:number)=>Number.isInteger(value)?String(value):String(Number(value.toFixed(2)));
export function resultExplanation(dataset:Dataset,result:Result){
 const rules=result.matchedRuleIds.map(id=>dataset.rules.find(rule=>rule.id===id)).filter(rule=>rule!==undefined);
 if(!rules.length)return "";
 const first=rules[0],dimension=first.dimensions[0],native=dimension.sourceNative;
 const range=native&&native.min!==null&&native.max!==null?`${formatNumber(native.min)}–${formatNumber(native.max)} ${native.unit}`:"the published range";
 const category=first.category&&first.category!=="source_not_explicit"?` ${first.category}`:"";
 const sizes=result.sizes.join(" or ");
 return `Your ${measurementNames[dimension.field]} measurement falls within ${first.brand}'s ${range}${category} chart range, which maps to size ${sizes}.`;
}
export function buildInput(brand:CalculatorBrand,v:{category?:string;primary?:number;height?:number;ktt?:number}):EngineInput{const c=brandInputs[brand];return {brand,...(v.category?{category:v.category}:{}),...(c.method==="floor_to_knee"?{floor_to_knee_in:v.primary}:{ankle_to_knee_in:v.primary}),...(v.height!==undefined?{height_in:v.height}:{}),...(v.ktt!==undefined?{knee_to_thigh_in:v.ktt}:{})}}
export function comparisonResults(dataset:Dataset,selected:CalculatorBrand,v:{category?:string;primary:number;height?:number;ktt?:number}){return (Object.keys(brandInputs) as CalculatorBrand[]).filter(name=>name!=="Vaughn").map(name=>{const c=brandInputs[name],active=brandInputs[selected];if(c.method!==active.method)return {brand:name,text:"Different measurement method needed."};if(c.category&&name!==selected)return {brand:name,text:"Brand-specific category needed."};if(c.height&&v.height===undefined)return {brand:name,text:"Standing height needed."};if(c.ktt&&v.ktt===undefined)return {brand:name,text:"Knee-to-thigh needed."};const r=recommend(dataset,buildInput(name,{...v,category:name===selected?v.category:undefined}));return {brand:name,text:r.sizes.length?r.sizes.join(" or "):statusHeading(r)}})}
export const comparisonHtml=(dataset:Dataset,selected:CalculatorBrand,v:{category?:string;primary:number;height?:number;ktt?:number})=>comparisonResults(dataset,selected,v).map(row=>`<div><strong>${row.brand}</strong><span>${row.text}</span></div>`).join("");
