import type {BrandSlug} from "../lib/content/brand-charts";
export interface BrandCopy { intro:string; howToRead:string[]; warningTitle:string; warning:string; marker:string }
export const brandCopy:Record<BrandSlug,BrandCopy>={
 bauer:{intro:"Bauer groups leg pads by age-level category and shin-height range. Choose the category first, then compare your floor-to-knee measurement with every matching row.",howToRead:["YOUTH, JUNIOR, INTERMEDIATE and SENIOR are separate chart sections.","Inclusive endpoints create real overlaps, so a boundary can legitimately show adjacent sizes.","An overlap is a fit-check decision, not permission to choose the larger pad automatically."],warningTitle:"Category and overlap matter",warning:"Do not compare a measurement against a different Bauer category. At an inclusive boundary, physically verify knee-block landing in both adjacent sizes.",marker:"Bauer category overlap"},
 ccm:{intro:"CCM publishes floor-to-knee ranges alongside exact height anchors. The height values are chart anchors, not interpolation bands.",howToRead:["Start with floor-to-knee, then use the published exact height anchor as a compatibility check.","Do not interpolate between height anchors or convert a nearby height into an invented row.","Size 24 is explicitly unsupported in this dataset because the reviewed source does not provide it."],warningTitle:"Exact height anchors only",warning:"A floor-to-knee match and a disjoint height anchor are a conflict. Stop rather than selecting the nearest height row.",marker:"CCM exact height no interpolation unsupported 24"},
 true:{intro:"TRUE separates JR, INT and SR ranges. Some measurements fall into intentional gaps between published rows; those gaps remain honest cannot-determine outcomes.",howToRead:["Select the published JR, INT or SR category before reading the range.","Inclusive endpoints may show adjacent sizes where rows touch.","A source gap is not a rounding problem and must not be filled with a nearest-size guess."],warningTitle:"Published gaps stay gaps",warning:"If your measurement falls between reviewed TRUE rows, the result is cannot determine. Recheck the measurement or consult a qualified fitter.",marker:"TRUE source gaps no nearest size"},
 warrior:{intro:"Warrior floor-to-knee ranges control base pad size. Published height anchors are advisory cross-checks, and thigh-rise availability is a separate discrete mapping.",howToRead:["Use floor-to-knee for the base size; do not make height the controlling measurement.","A height anchor can expose a conflict when it points to a disjoint size, but an unlisted height does not erase a valid FTK match.","A blank extension cell means no reviewed value was published; an explicit N/A means the reviewed chart says that extension is unavailable."],warningTitle:"Blank and N/A are different",warning:"Never convert a blank mapping into zero or treat N/A as an available extension. Verify thigh rise and knee landing physically.",marker:"Warrior advisory height blank versus N/A"},
 brians:{intro:"Brian's rows are exact tool-verified ankle-to-knee plus knee-to-thigh tuples. They are provisional evidence, not broad interpolated ranges.",howToRead:["Both measurements must exactly match one reviewed tuple.","Do not interpolate between tuples or substitute floor-to-knee for ankle-to-knee.","Every output carries the tool-verified provisional badge and requires a physical knee-block check."],warningTitle:"Tool-verified provisional",warning:"Knee-block verification is mandatory before relying on a Brian's result. No exact tuple means cannot determine.",marker:"Brian's provisional badge knee-block verification"}
};
